name: Notificacion Push Main

on:
  push:
    branches:
      - main

jobs:
  notificar:
    runs-on: ubuntu-latest

    steps:
      - name: Enviar notificación a ntfy
        run: |
          curl -H "Title:  Nuevo Push en main chicooo" \
               -H "Priority: high" \
               -d "Se ha subido nuevo código al repositorio ${{ github.repository }} por ${{ github.actor }}" \
               https://ntfy.sh/DevOps-itla
